# -*- coding: utf-8 -*-
"""test.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Aemu7_i2gYcMbi3G7OmP-3Ui6zHWBffo

## Sarah Test
"""

class conversion():
    def __init__ (self, conversion):
        self.conversion = []

    def convert(number, units, convert):
        try:
            number = int(number)
        except ValueError:
            return 'Error. Please retry. Make sure you enter a number and not a letter.'
        units = units
        convert = convert
        if units == 'C' and convert == 'F':
            answer = int(number) * (9/5) + 32
        elif units == 'C' and convert == 'K':
            answer = int(number) + 273.15
        elif units == 'C' and convert == 'C':
            answer = number
        elif units == 'F' and convert == 'C':
            answer = (int(number) - 32) * (5/9)
        elif units == 'F' and convert == 'K':
            answer = (int(number) - 32) * (5/9) + 273.15
        elif units == 'F' and convert == 'F':
            answer = number
        elif units == 'K' and convert == 'F':
            answer = (int(number) - 273.15) * (9/5) + 32
        elif units == 'K' and convert == 'C':
            answer = int(number) - 273.15
        elif units == 'K' and convert == 'K':
            answer = number
        else:
            print('Error. Please retry. Make sure you type in (#, original unit, new unit).')

        return 'Conversion: ' + str(number) + str(units) + ' = ' + str(answer) + str(convert)

conversion.convert('10','C','K')

